// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for windows - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSrnAYXvcYL_j9K9ty-dHs71ZwvUIH1ZE',
    appId: '1:93548267324:web:5cebde207b8de11ec60039',
    messagingSenderId: '93548267324',
    projectId: 'ssip-hackathon2022',
    authDomain: 'ssip-hackathon2022.firebaseapp.com',
    storageBucket: 'ssip-hackathon2022.appspot.com',
    measurementId: 'G-VPBK8SVKQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO5jDtig1l-ygKcPMTpBCdhlM0540Q0vg',
    appId: '1:93548267324:android:20bed5b45fc529d1c60039',
    messagingSenderId: '93548267324',
    projectId: 'ssip-hackathon2022',
    storageBucket: 'ssip-hackathon2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOzjJ1BRVl0_KyT6dIJ0e3Z3aTESvI0Nk',
    appId: '1:93548267324:ios:b148048756aa342bc60039',
    messagingSenderId: '93548267324',
    projectId: 'ssip-hackathon2022',
    storageBucket: 'ssip-hackathon2022.appspot.com',
    iosClientId:
        '93548267324-emihsmcbvgtcj5499cs5me7so37ua61b.apps.googleusercontent.com',
    iosBundleId: 'net.codeveer.ssipHackathon2022',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOzjJ1BRVl0_KyT6dIJ0e3Z3aTESvI0Nk',
    appId: '1:93548267324:ios:b148048756aa342bc60039',
    messagingSenderId: '93548267324',
    projectId: 'ssip-hackathon2022',
    storageBucket: 'ssip-hackathon2022.appspot.com',
    iosClientId:
        '93548267324-emihsmcbvgtcj5499cs5me7so37ua61b.apps.googleusercontent.com',
    iosBundleId: 'net.codeveer.ssipHackathon2022',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBO5jDtig1l-ygKcPMTpBCdhlM0540Q0vg',
    appId: '1:93548267324:android:20bed5b45fc529d1c60039',
    messagingSenderId: '93548267324',
    projectId: 'ssip-hackathon2022',
    storageBucket: 'ssip-hackathon2022.appspot.com',
  );
}
